### ISSUE TITLE
Translation is both on GitHub and Zanata

### ISSUE THREAD

**Issue by scootergrisen** [OpenPrinting/system-config-printer#114]
I see the translation for system-config-printer both here and on Zanata (https://fedora.zanata.org/project/view/system-config-printer?dswid=7984).

This is not good i think i translated the missing strings and then afterwards i see they are already translated here.

So i would like the translation to only happen one place and then if other places need the translation then can get them from the main place so the translation is the same and people dont have to upload the translation multiple places.

**Comment by zdohnal** [comment]
Hi,
I understand you. The primary place for s-c-p is Zanata and I encourage people to translate strings there, but some of them don't have permissions to do so, or they don't want to add it there, so they create pull requests here.
I would like to keep translations in Zanata, because it has IMO good feature like confirming correctness of translations or progress of overall translation, so when I want to release new version, then I merge translation from both places with Zanata as priority.

**Comment by scootergrisen** [comment]
If Zanata is the primary place then it does not make sense that the translation there is not translated but here on GitHub it is.
Surely the primarly place should be the place with the more fully translation.

**Comment by zdohnal** [comment]
Translation are now handled by weblate, closing.

**Comment by scootergrisen** [comment]
https://github.com/OpenPrinting/system-config-printer/wiki needs updating.
