### ISSUE TITLE
The printer queue does not support changing the order

### ISSUE THREAD

**Issue by whailiang** [OpenPrinting/system-config-printer#171]
The printer queue switching sequence should be a very important function for users

**Comment by whailiang** [comment]
I want to discuss this feature with the developer
    Thanks

**Comment by zdohnal** [comment]
Hi @whailiang ,

I'm Zdenek and I'm the current system-config-printer developer/maintainer.

Would you mind telling me what do you mean by 'changing the order'? Do you mean the order of print jobs on the queue?

system-config-printer is only GUI above CUPS, so it is capable of operations which are doable in CUPS at most.
AFAIK print queue in CUPS works as FIFO, unable to change the print job order. User can move the job to other queue, cancel it, reprint it or resume it printing.

So if there is no way how to do it in CUPS, system-config-printer is not able to do it too - and s-c-p is currently in maintenance mode, so every possible new features should be critical.

**Comment by whailiang** [comment]
Hello @zdohnal , you are right. System-config-printer is the upper GUI of cups. What I want to say is whether we can modify the priority of printing tasks to modify the order of printing. I think users can pass system-config- The printer can not only realize the printing function, but also can change the printing order. Imagine if many files in the print queue are printing, but you now have a very important file to print, is it necessary to put the printer in the queue Cancel all tasks and print this very important document? The answer is no. We need to modify the priority of a certain print task to improve its printing order. What do you think?

**Comment by zdohnal** [comment]
@whailiang It is an interesting idea, but it is out of scope for system-config-printer right now. Applications communicate with cupsd or printer itself (gtk dialogs at the moment) during printing, not with system-config-printer. So the prioritization would need to be supported in cupsd and device itself before it can be somehow implemented in python-cups/system-config-printer.

Since it is not feature for s-c-p now, I'm closing the issue.
