### ISSUE TITLE
Translation update

### ISSUE THREAD

**Issue by Mejans** [OpenPrinting/system-config-printer#186]
Hello,
I was wondering, how often are the translations update?
I see a release 12 days ago but the po folder hasn't changed in 7 months =/
I personally made changed on the weblate, that's why I'm tracking the releases ^^

**Comment by zdohnal** [comment]
Hi,

> I was wondering, how often are the translations update?

It depends how often pull requests from Weblate comes.

> I see a release 12 days ago but the po folder hasn't changed in 7 months =/

A new release and a translation update don't need to have the same change dates. The newest release just contains all translation PR from weblate since the previous release.

> I personally made changed on the weblate, that's why I'm tracking the releases ^^

When did you make the changes?

If the changes are older than 7 months, then system-config-printer should contain them. If they are not, Weblate should create a PR for them, because weblate creates a PR when there is an translation update and then I merge it.

**Please check the following things:**
1) Please check whether your translations are already in system-config-printer project by checking the specific .po file you have changed.
2) If the changes aren't there, please check whether your translations are in weblate - if they are there already, please contact the server admin (https://translate.fedoraproject.org/contact/) about weblate not creating PRs with updates for projects.
3) If your changes aren't even in weblate, then please make them.

**Comment by Mejans** [comment]
Hello,
thanks for the answers.
Not, my changes are not older than 7 months ago.
They are here: https://translate.fedoraproject.org/projects/system-config-printer/master/oc/
But on GitHub I don't see any PR from weblate about them.

**Comment by zdohnal** [comment]
It seems weblate has some alerts - I'll check it with weblate admins how to fix it.

Right now, I merged new updates from weblate manually, please check.

**Comment by Mejans** [comment]
Yes, well imported :) 
Thanks!
