### ISSUE TITLE
fix for autoconf 2.70 needed

### ISSUE THREAD

**Issue by andyrtr** [OpenPrinting/system-config-printer#201]
With recent [autoconf 2.70](https://lists.gnu.org/archive/html/autoconf/2020-12/msg00002.html) you will get this error when running autoreconf -vfi:

```configure.ac: error: AM_GNU_GETTEXT is used, but not AM_GNU_GETTEXT_VERSION or AM_GNU_GETTEXT_REQUIRE_VERSION```

I could solve it adding this small patch. Not sure if gettext 0.21 is needed or even an older version would do it.
```--- system-config-printer-1.5.14/configure.ac   2021-01-06 09:03:08.000000000 +0100
+++ system-config-printer-1.5.14/configure.ac.new       2021-01-06 10:38:51.997694866 +0100
@@ -3,6 +3,7 @@
 AM_INIT_AUTOMAKE([dist-xz dist-bzip2 subdir-objects 1.6])
 IT_PROG_INTLTOOL
 AM_GNU_GETTEXT([external])
+AM_GNU_GETTEXT_VERSION(0.21)
 AM_PATH_PYTHON([3])
 PACKAGE="AC_PACKAGE_NAME"
 VERSION="AC_PACKAGE_VERSION"```

And please add the missing README file to avoid another autotools error. I've added "touch README" to our Arch packaging script for a long time.

**Comment by zdohnal** [comment]
Hi @andyrtr ,

thank you for reporting the issue!

My Fedora rawhide has only autoconf 2.69, would you mind testing if adding the following line in configure.ac works?

```
AM_GNU_GETTEXT_VERSION([0.18.3])
```

I chose this version because it is the same version as cups-filters requires and I would like to require the same version as other projects of printing stack.

**Comment by andyrtr** [comment]
Works well too here.

**Comment by zdohnal** [comment]
Fixed on the current master.

Thank you for the report and testing!
