### ISSUE TITLE
Shutdown system with printer connected

### ISSUE THREAD

**Issue by gnayils** [OpenPrinting/system-config-printer#296]
Shutdown the system with printer connected via USB, after the system completely power off, plug-out the printer, then power on the system, when the system started up, the "lpstat -t" shows the printer still idle.

**Comment by zdohnal** [comment]
Hi,

that's expected - udev-configure-printer service reacts on udev messages, which are generated during runtime. So if you unplug the device when the system is turned off, no udev message is generated for the service to catch and the device is not removed.
The service is designed for plug-in/plug-out during system's runtime, and cupsd itself doesn't check status of HW printers at the start (it checks the status once you want to print to the print queue).

**Comment by gnayils** [comment]
Is there have any solution or workaround to fix this issue? like to force refresh the printers status during system startup or something?

**Comment by zdohnal** [comment]
Either unplug the printer when OS is running, which removes your print queue automatically, or (if you unplugged the printer when the PC was turned off) remove the print queue by ```lpadmin -x <queue_name>```.

Or alternative way, in case your device support IPP-over-USB (how-to find out [here](https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_how_to_find_out_if_my_usb_device_supports_ipp_over_usb)), mask the service template by ```sudo systemctl mask configure-printer@.service```, remove the lingering permanent queue by ```lpadmin -x```, install ```ipp-usb``` and plug the printer in. Then the ```ipp-usb``` service will create an IPP service which will be advertised on mDNS communication - the applications can pick up this ```temporary``` queue via CUPS API (if the app uses the API back from 2016) if the printer is plugged in and turn on - the queue won't be seen otherwise.

**Comment by gnayils** [comment]
Thanks for your suggestions, I will try it later.
