### ISSUE TITLE
Improvements to the printer queue

### ISSUE THREAD

**Issue by Lehmeiers** [OpenPrinting/system-config-printer#298]
Hello!
I have a suggestion for improvement.
Would it be possible to show the pages that are to be printed and that are already printed?

An example:
I have a document that has 30 pages and I want to print it 10 times.

Now I have the problem that the print queue shows the size of the file and when it was started but not how much of it has already been printed or how long the job will probably take.

If I set it to print a complete document each time before starting the next one, it should show, for example, 3 copies finished and now the 11 page (of the 4th copy).

If I set it to print one page for each copy, it could show e.g. I am now at 30 times page 9 and 5 times page 10.

This would show the progress better than the current version.

Perhaps also the probable printing time for the remaining print job.

I hope that I have explained my request well and that it meets with a positive response from you.

Many thanks in advance.

Sincerely R.Lehmeier

Translated with www.DeepL.com/Translator (free version)

**Comment by zdohnal** [comment]
Hi @Lehmeiers ,

thank you for the idea!

Unfortunately this would need a implementation of such feature in the printer itself, which cupsd can process and send to a GUI frontend as s-c-p is.
AFAIK there isn't such a feature proposed or implemented in IPP standard at the moment, so there is not much to do in s-c-p.

**Comment by zdohnal** [comment]
IMO it is the best to sent an email to printing-architecture@lists.linux-foundation.org . There are people who develop CUPS and write IPP standards, so they will know whether this feature is already implemented in the code, or is written in standard or hasn't been written yet because of various reasons.

To be clear, I'm CUPS release manager as well, and AFAIK we don't implement such feature - yes, there is page counting during filtering and sending the file to the printer, but unless a printer answers like "Page 10 finished", cupsd doesn't give a honest report how the job is going. Currently we just monitor general statuses of the printer and the job like 'Stopped', 'Processing', 'Completed', because such statuses are defined in IPP standard. Additionally this logically doesn't/won't work for printers connected via socket/lpd/usb, because such setups don't communicate via IPP protocol.
