### ISSUE TITLE
Can't build this software

### ISSUE THREAD

**Issue by kacperpaczos** [OpenPrinting/system-config-printer#339]
I used the commands to build this software from README and I have:

> checking pkg-config is at least version 0.9.0... yes
> checking for CUPS SERVERBIN dir... configure: error: No CUPS pkgconfig file present and no CUPS SERVERBIN dir defined in configure options.
> make: *** No targets specified and no makefile found.  Stop.
> [sudo] password for kacper:         
> make: *** No rule to make target 'install'.  Stop.

What am I doing wrong?

**Comment by zdohnal** [comment]
Do you have build requirements installed? The message says it cannot find CUPS pkgconfig file, which is in CUPS since series 2.4.x - so you might have missing CUPS development files, or your CUPS is too old. If CUPS is too old, you have to define the path yourself (usually /usr/lib/cups) as configure option.
