### ISSUE TITLE
Enhancement - Clarify the media types by giving the paper weight in gsm

### ISSUE THREAD

**Issue by cutlery** [OpenPrinting/system-config-printer#380]
Hi,

Under a printer's "Properties" > "Printer Options" > "Media Type" we have a list of paper types, but a little guidance to the end user could help a great deal.  My suggestion would be to put the range of what is considered "plain", "thick" and "thicker", e.g. "75-85gsm" for plain paper.  The description can be part of the label in the dropdown menu after the Media Type, or maybe a balloon when hovering over the dropdown item.
Unless I'm barking up the wrong tree, and all of this should be defined in the printer-specific PPD instead?

Anyway, here is my suggested list for the paper types in Media Types, including a different sort order (I also don't like the pretentious capitalisation of every word called title case, but that's not so relevant now):

* Plain paper (75-105gsm)
* Recycled paper (75-105gsm)
* Thin paper (60-75gsm)
* Thick paper (105-163gsm)
* Thicker paper (163gsm and above)
* Bond paper (60-161gsm)
* Envelopes (75-90gsm)
* Thin envelopes (below 75gsm)
* Thick envelopes (above 90gsm)

A little text could say that these are only guidelines, as much depends on the paper pulp quality of the paper, the smoothness,  storage duration and environment, and printing device to determine how much voltage (resulting in higher heat) the laser printer needs to use for an optimal print output (not sure about inkjet).

I assume one needs to update the file ppdippstr.py to reflect the above suggested changes?  I'm not sure why the strings are defined under \#Samsung though.

P.S.: FWIW, I have a Brother monochrome laser printer and have installed Brother's official packages (with one tweak to a package's dependencies).  OS is Debian/testing.

Let me know what you think about it.  Thanks for your consideration.

**Comment by zdohnal** [comment]
If the printer uses PPD which is not generated from IPP protocol (in general the printer uses IPP Everywhere/Airprint standards aka driverless standards) all human readable texts (like you proposed) has to be in the PPD provided by printer driver vendor.
Otherwise CUPS can generate PPD at the moment for printers using driverless standards, where we could adjust human text internally if it is not restricted by a standard (IIRC some of those strings are standardized by IANA). But nothing else for classic PPDs.

In s-c-p we get option texts via pycups python module (which uses libcups) and then we try to find this text from PPD in dictionary defined in ppdippstr module (if it is missing in the dict, the original text is used), so still we need it defined in the PPD for those cases.

Something like this I could see in CUPS if IPP attributes had some new member "info" or human readable text was enhanced for driverless printers, but classic PPDs would have to be covered by enhancing the PPD (like I was thinking about adding something like this into libppd, but IMHO we don't have enough expertise to provide detailed information messages like this - printer driver vendor should know its printers best, so they could be a source of valid information).

Either way, thank you for the idea!
